#!/bin/bash

# Usage
# . lg-env                    (set lab environment variables)

# Set the lab parameters (replace these with your own)
export LG_CROSSBAR=ws://kea:20408/ws
export LG_ENV=/vid/software/devel/ubtest/lab/env_rpi_try.cfg
export UB_TEST_HOOKS=/vid/software/devel/ubtest/u-boot-test-hooks
