#!/bin/bash

# Script to do a bisect to locate a U-Boot failure on a particular target
# This starts 'git bisect run' with the 'ub-try' script
# Before using this you must set the 'good' and 'bad' commits with
# 'git bisect good ...' and 'git bisect bad ...'

usage() {
	echo "Failed: $1"
	echo
	echo "Usage: ub-bisect [-cs] <target> [<commit>]"
	echo " -c  Run 'make mrproper' before building"
	echo " -s  Send over USB (instead of writing to boot media)"
	exit 1
}

allowed_args="cnstv"
mydir=$(dirname $0)

. ${mydir}/lg-env

allowed_args="cs"
. ${mydir}/get_args.sh

commit="$1"

# If we will be cherry-picking and using 'git reset', make sure there is no
# modified code in the directory
if [ -n "${commit}" ] && [ -n "$(git status --porcelain)" ]; then
	echo "Working directory must be clean"

	# abort the bisect (values >127 abort)
	exit 128
fi

echo "Starting bisect on target ${target} - cherry-pick commit: ${commit}"
git bisect run _ub-bisect-try ${commit}
