#!/bin/bash

# Boot U-Boot to the command prompt on a particular target and bring up a
# console

usage() {
	if [ -n "$1" ]; then
		echo "Failed : $1"
	else
		echo "Connect to a running U-Boot ready, to enter commands"
	fi
	echo "Usage: ub-cli [-csv] <target>"
	echo " -B  Don't build U-Boot"
	echo " -c  Run 'make mrproper' before building"
	echo " -d  Set build directory"
	echo " -D  Enable debugging"
	echo " -h  Help"
	echo " -s  Send over USB (instead of writing to boot media)"
	echo " -T  Don't bootstrap U-Boot"
	echo " -v  Verbose mode"
	exit 1
}

mydir=$(dirname $0)

. ${mydir}/lg-env

allowed_args="BcDhsTv"
. ${mydir}/get_args.sh

ret=0
labgrid-client ${V} ${debug} ${vars} -r ${target} -s uboot -a console || ret=$?

labgrid-client ${V} -r "${target}" release -a

[[ $ret -ne 0 ]] && exit $ret
