#!/bin/bash

# Boot U-Boot on a particular target and bring up a console. This does not wait
# for the command prompt to appear - output is shown as soon as it appears.

usage() {
	if [ -n "$1" ]; then
		echo "Failed : $1"
	else
		echo "Connect to the board console interactively"
	fi
	echo "Usage: ub-int [-csv] <target>"
	echo " -B  Don't build U-Boot"
	echo " -c  Run 'make mrproper' before building"
	echo " -d  Set build directory"
	echo " -h  Help"
	echo " -R  Don't reset the board, just connect as is"
	echo " -s  Send over USB (instead of writing to boot media)"
	echo " -T  Don't bootstrap U-Boot"
	echo " -v  Verbose mode"
	exit 1
}

mydir=$(dirname $0)

. ${mydir}/lg-env

allowed_args="d:cBhRsTv"
. ${mydir}/get_args.sh

ret=0
labgrid-client ${V} ${vars} -r ${target} ${strategy} -a console || ret=$?

labgrid-client ${V} -r "${target}" release -a

[[ $ret -ne 0 ]] && exit $ret
