#!/bin/bash

# Boot U-Boot on a particular target and run selected tests

usage() {
	if [ -n "$1" ]; then
		echo "Failed : $1"
	else
		echo "Run a U-Boot pytest on a board"
	fi
	echo "Usage: ub-pyt [-cnst] <target> <test_spec>"
	echo " -B  Don't build U-Boot"
	echo " -c  Run 'make mrproper' before building"
	echo " -h  Help"
	echo " -R  Don't reset the board, just connect as is"
	echo " -s  Send over USB (instead of writing to boot media)"
	echo " -T  Don't bootstrap U-Boot"
	echo
	echo "<test_spec> is the tests to run, e.g. not tpm"
	exit 1
}

mydir=$(dirname $0)

. ${mydir}/lg-env

allowed_args="BchRsT"
. ${mydir}/get_args.sh

tmpfile=$(mktemp)

env=

[ -n "${strategy}" ] && strategy="-s uboot"

# no_prompt_wait comes from the get_args.sh script. It is either empty, or
# contains --no-prompt-wait

# Try the --role option if it exists
if grep -q -- "--role" test/py/conftest.py; then
	PYTHONPATH="${UB_TEST_HOOKS}/py/$hostname" ./test/py/test.py -s \
		--configure ${no_prompt_wait} --role "${target}" -k "$*"
else
	# Find out the board name and path
	if lg-client -r "${target}" -a query UBootProviderDriver:board,build_path \
			> "${tmpfile}"; then
		readarray -t a < ${tmpfile}
		rm ${tmpfile}
		board="${a[0]}"
		build_path="${a[1]}"
	else
		echo "Failed to obtain build information"
		exit 1
	fi

	# Run the tests, using this information
	PYTHONPATH="${UB_TEST_HOOKS}/py/$hostname" ./test/py/test.py \
		--bd "${board}" --configure ${no_prompt_wait} ${slow_serial} \
		${env} --build-dir "${build_path}" --id "${target}" -k "$*"
fi
