#!/bin/bash

# Boot U-Boot on a particular target and run selected tests

usage() {
	echo "Failed: $1"
	echo
	echo "Usage: ub-pyt [-cnst] <target> <test_spec>"
	echo " -c  Run 'make mrproper' before building"
	echo " -n  Don't build U-Boot"
	echo " -r  Don't reset the board, just connect as is"
	echo " -s  Send over USB (instead of writing to boot media)"
	echo " -t  Don't bootstrap U-Boot"
	echo
	echo "<test_spec> is the tests to run, e.g. not tpm"
	exit 1
}

mydir=$(dirname $0)

. ${mydir}/lg-env

allowed_args="cnrst"
. ${mydir}/get_args.sh

tmpfile=$(mktemp)

# Find out the board name and path
if lg-client -r "${target}" -a query UBootProviderDriver:board,build_path \
	SerialDriver:txdelay,spl_banner_times > "${tmpfile}"; then
	readarray -t a < ${tmpfile}
	rm ${tmpfile}
	board="${a[0]}"
	build_path="${a[1]}"
	delay="${a[2]}"
	spl_banner_times="${a[3]}"
else
	echo "Failed to obtain build information"
	exit 1
fi

env=

[ "${delay}" != "0.0" ] && slow_serial="--slow-serial"
[ "${spl_banner_times}" != "None" ] && env+=" --env spl_banner_times=${spl_banner_times}"

[ -n "${strategy}" ] && strategy="-s uboot"

# Run the tests, using this information
PYTHONPATH="${UB_TEST_HOOKS}/py/$hostname" ./test/py/test.py \
	--bd "${board}" --configure ${no_prompt_wait} ${slow_serial} ${env} \
	--build-dir "${build_path}" --id "${target}" -k "$*"
